FROM python:3.13-slim

# Install Node.js
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean

WORKDIR /app

# Copy project
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r chatbot/requirements.txt

# Install Node dependencies
RUN cd server && npm install

EXPOSE 10000

WORKDIR /app/server

CMD ["npm", "start"]